### ISSUE TITLE
Config is ignored

### ISSUE THREAD

**Issue by mik01aj** [DanPurdy/linter-sass-lint#9]
I get a lot of warnings from my scss.

So I created this config:

```
options:
    merge-default-rules: true # Argh. https://github.com/sasstools/sass-lint/issues/308

files:
    include: 'mockups/**/*.scss'
    ignore:
        - 'app/styles/legacy/**/*.*'
        - 'mockups/**/vendor/**/*'

rules:
    # ignoring EVERYTHING
    border-zero: 0
    brace-style: 0
    clean-import-paths: 0
    empty-args: 0
    empty-line-between-blocks: 0
    extends-before-declarations: 0
    extends-before-mixins: 0
    final-newline: 0
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0
    function-name-format: 0
    hex-length: 0
    hex-notation: 0
    indentation: 0
    leading-zero: 0
    mixin-name-format: 0
    mixins-before-declarations: 0
    nesting-depth: 0
    no-color-keywords: 0
    no-color-literals: 0
    no-css-comments: 0
    no-debug: 0
    no-duplicate-properties: 0
    no-empty-rulesets: 0
    no-extends: 0
    no-ids: 0
    no-important: 0
    no-invalid-hex: 0
    no-mergeable-selectors: 0
    no-misspelled-properties: 0
    no-qualifying-elements: 0
    no-trailing-zero: 0
    no-transition-all: 0
    no-url-protocols: 0
    no-vendor-prefixes: 0
    no-warn: 0
    one-declaration-per-line: 0
    placeholder-in-extend: 0
    placeholder-name-format: 0
    property-sort-order: 0
    quotes: 0
    shorthand-values: 0
    single-line-per-selector: 0
    space-after-bang: 0
    space-after-colon: 0
    space-after-comma: 0
    space-before-bang: 0
    space-before-brace: 0
    space-before-colon: 0
    space-between-parens: 0
    trailing-semicolon: 0
    url-quotes: 0
    variable-for-property: 0
    variable-name-format: 0
    zero-unit: 0
```

And put it in `.sass-lint.yml` in my project. It changed nothing in linting. So I added the absolute path of this config in the plugin preferences. Still no change. So I added the absolute path of my locally installed `sass-lint` in the plugin preferences. Still no change. Then I restarted Atom. Still no change. 

`sass-lint`, however, when run from CLI on this file (`sass-lint -c .sass-lint.yml -v app/styles/_mobile.scss`) reports no errors.

So, from what I understand, any config I have is just ignored by this plugin. :(
